# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TMDB App' do

pod 'SDWebImage', '~> 3.7.5'
pod 'MMDrawerController', '~> 0.6.0'
pod 'AFNetworking', '~> 3.0.4'

end

target 'TMDB AppTests' do

end

target 'TMDB AppUITests' do

end

