# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Lesson 21' do

pod 'MMDrawerController', '~> 0.6.0'
pod 'SDWebImage', '~> 3.7.4'

end

target 'Lesson 21Tests' do

end

target 'Lesson 21UITests' do

end

